version: '3'
services:
  express-backend:
    container_name: express-backend-diplo
    image: diplo/express-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  datadog:
    container_name: dd-agent-datadog
    image: datadog/agent
    environment:
      - DD_API_KEY=02bca40cdf633b6ce04ec4776d5b5123
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_HOSTNAME=dd-agent-diplo
      - DD_LOG_LEVEL=debug
