version: '2'
services:
  express-backend:
    container_name: express-backend-diplo
    image: diplo/express-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  datadog:
    container_name: dd-agent-datadog
    image: datadog/docker-dd-agent
    environment:
     - DD_API_KEY=02bca40cdf633b6ce04ec4776d5b5123
     - DD_SITE="datadoghq.com"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
